
export interface NumberPreset {
  id: string;
  label: string;
  decimalSeparator: 'dot' | 'comma';
  thousandSeparator: 'space' | 'comma' | 'dot' | 'nbsp' | 'none';
  rangeSymbol: string;
  rangeSpacing: 'space' | 'no-space';
  numberSign: string;
  numberSignSpacing: 'space' | 'no-space';
  digitToTextMap: { digit: number, forms: string[] }[];
}

export const NUMBER_PRESETS: NumberPreset[] = [
  { id: 'sq', label: 'Albanian', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['një'] }, { digit: 2, forms: ['dy'] }, { digit: 3, forms: ['tre'] }, { digit: 4, forms: ['katër'] }, { digit: 5, forms: ['pesë'] }, { digit: 6, forms: ['gjashtë'] }, { digit: 7, forms: ['shtatë'] }, { digit: 8, forms: ['tetë'] }, { digit: 9, forms: ['nëntë'] } ] },
  { id: 'ar', label: 'Arabic', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'رقم', numberSignSpacing: 'space', digitToTextMap: [] },
  { id: 'bg', label: 'Bulgarian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['нула'] }, { digit: 1, forms: ['един'] }, { digit: 2, forms: ['две'] }, { digit: 3, forms: ['три'] }, { digit: 4, forms: ['четири'] }, { digit: 5, forms: ['пет'] }, { digit: 6, forms: ['шест'] }, { digit: 7, forms: ['седем'] }, { digit: 8, forms: ['осем'] }, { digit: 9, forms: ['девет'] } ] },
  { id: 'zh-CN', label: 'Chinese (S)', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['零'] }, { digit: 1, forms: ['一'] }, { digit: 2, forms: ['二'] }, { digit: 3, forms: ['三'] }, { digit: 4, forms: ['四'] }, { digit: 5, forms: ['五'] }, { digit: 6, forms: ['六'] }, { digit: 7, forms: ['七'] }, { digit: 8, forms: ['八'] }, { digit: 9, forms: ['九'] } ] },
  { id: 'zh-TW', label: 'Chinese (T)', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['零'] }, { digit: 1, forms: ['一'] }, { digit: 2, forms: ['二'] }, { digit: 3, forms: ['三'] }, { digit: 4, forms: ['四'] }, { digit: 5, forms: ['五'] }, { digit: 6, forms: ['六'] }, { digit: 7, forms: ['七'] }, { digit: 8, forms: ['八'] }, { digit: 9, forms: ['九'] } ] },
  { id: 'hr', label: 'Croatian', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'br.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nula'] }, { digit: 1, forms: ['jedan'] }, { digit: 2, forms: ['dva'] }, { digit: 3, forms: ['tri'] }, { digit: 4, forms: ['četiri'] }, { digit: 5, forms: ['pet'] }, { digit: 6, forms: ['šest'] }, { digit: 7, forms: ['sedam'] }, { digit: 8, forms: ['osam'] }, { digit: 9, forms: ['devet'] } ] },
  { id: 'cs', label: 'Czech', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'č.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nula'] }, { digit: 1, forms: ['jeden'] }, { digit: 2, forms: ['dva'] }, { digit: 3, forms: ['tři'] }, { digit: 4, forms: ['čtyři'] }, { digit: 5, forms: ['pět'] }, { digit: 6, forms: ['šest'] }, { digit: 7, forms: ['sedm'] }, { digit: 8, forms: ['osm'] }, { digit: 9, forms: ['devět'] } ] },
  { id: 'da', label: 'Danish', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nul'] }, { digit: 1, forms: ['en'] }, { digit: 2, forms: ['to'] }, { digit: 3, forms: ['tre'] }, { digit: 4, forms: ['fire'] }, { digit: 5, forms: ['fem'] }, { digit: 6, forms: ['seks'] }, { digit: 7, forms: ['syv'] }, { digit: 8, forms: ['otte'] }, { digit: 9, forms: ['ni'] } ] },
  { id: 'nl', label: 'Dutch', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'Nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nul'] }, { digit: 1, forms: ['een'] }, { digit: 2, forms: ['twee'] }, { digit: 3, forms: ['drie'] }, { digit: 4, forms: ['vier'] }, { digit: 5, forms: ['vijf'] }, { digit: 6, forms: ['zes'] }, { digit: 7, forms: ['zeven'] }, { digit: 8, forms: ['acht'] }, { digit: 9, forms: ['negen'] } ] },
  { id: 'en-US', label: 'English', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['one'] }, { digit: 2, forms: ['two'] }, { digit: 3, forms: ['three'] }, { digit: 4, forms: ['four'] }, { digit: 5, forms: ['five'] }, { digit: 6, forms: ['six'] }, { digit: 7, forms: ['seven'] }, { digit: 8, forms: ['eight'] }, { digit: 9, forms: ['nine'] } ] },
  { id: 'et', label: 'Estonian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: 'nr', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['null'] }, { digit: 1, forms: ['üks'] }, { digit: 2, forms: ['kaks'] }, { digit: 3, forms: ['kolm'] }, { digit: 4, forms: ['neli'] }, { digit: 5, forms: ['viis'] }, { digit: 6, forms: ['kuus'] }, { digit: 7, forms: ['seitse'] }, { digit: 8, forms: ['kaheksa'] }, { digit: 9, forms: ['üheksa'] } ] },
  { id: 'fi', label: 'Finnish', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'space', numberSign: 'nro', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nolla'] }, { digit: 1, forms: ['yksi'] }, { digit: 2, forms: ['kaksi'] }, { digit: 3, forms: ['kolme'] }, { digit: 4, forms: ['neljä'] }, { digit: 5, forms: ['viisi'] }, { digit: 6, forms: ['kuusi'] }, { digit: 7, forms: ['seitsemän'] }, { digit: 8, forms: ['kahdeksan'] }, { digit: 9, forms: ['yhdeksän'] } ] },
  { id: 'fr-FR', label: 'French', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: 'à', rangeSpacing: 'space', numberSign: 'n°', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['zéro'] }, { digit: 1, forms: ['un', 'une'] }, { digit: 2, forms: ['deux'] }, { digit: 3, forms: ['trois'] }, { digit: 4, forms: ['quatre'] }, { digit: 5, forms: ['cinq'] }, { digit: 6, forms: ['six'] }, { digit: 7, forms: ['sept'] }, { digit: 8, forms: ['huit'] }, { digit: 9, forms: ['neuf'] } ] },
  { id: 'de-DE', label: 'German', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: 'Nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['null'] }, { digit: 1, forms: ['eins'] }, { digit: 2, forms: ['zwei'] }, { digit: 3, forms: ['drei'] }, { digit: 4, forms: ['vier'] }, { digit: 5, forms: ['fünf'] }, { digit: 6, forms: ['sechs'] }, { digit: 7, forms: ['sieben'] }, { digit: 8, forms: ['acht'] }, { digit: 9, forms: ['neun'] } ] },
  { id: 'el', label: 'Greek', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'Αρ.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['μηδέν'] }, { digit: 1, forms: ['ένα'] }, { digit: 2, forms: ['δύο'] }, { digit: 3, forms: ['τρία'] }, { digit: 4, forms: ['τέσσερα'] }, { digit: 5, forms: ['πέντε'] }, { digit: 6, forms: ['έξι'] }, { digit: 7, forms: ['επτά'] }, { digit: 8, forms: ['οκτώ'] }, { digit: 9, forms: ['εννέα'] } ] },
  { id: 'he', label: 'Hebrew', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'מס\'', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['אפס'] }, { digit: 1, forms: ['אחת'] }, { digit: 2, forms: ['שתיים'] }, { digit: 3, forms: ['שלוש'] }, { digit: 4, forms: ['ארבע'] }, { digit: 5, forms: ['חמש'] }, { digit: 6, forms: ['שש'] }, { digit: 7, forms: ['שבע'] }, { digit: 8, forms: ['שמונה'] }, { digit: 9, forms: ['תשע'] } ] },
  { id: 'is', label: 'Icelandic', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['núll'] }, { digit: 1, forms: ['einn'] }, { digit: 2, forms: ['tveir'] }, { digit: 3, forms: ['þrír'] }, { digit: 4, forms: ['fjórir'] }, { digit: 5, forms: ['fimm'] }, { digit: 6, forms: ['sex'] }, { digit: 7, forms: ['sjö'] }, { digit: 8, forms: ['átta'] }, { digit: 9, forms: ['níu'] } ] },
  { id: 'it', label: 'Italian', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'n.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['uno'] }, { digit: 2, forms: ['due'] }, { digit: 3, forms: ['tre'] }, { digit: 4, forms: ['quattro'] }, { digit: 5, forms: ['cinque'] }, { digit: 6, forms: ['sei'] }, { digit: 7, forms: ['sette'] }, { digit: 8, forms: ['otto'] }, { digit: 9, forms: ['nove'] } ] },
  { id: 'ja', label: 'Japanese', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '～', rangeSpacing: 'no-space', numberSign: 'No.', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['零'] }, { digit: 1, forms: ['一'] }, { digit: 2, forms: ['二'] }, { digit: 3, forms: ['三'] }, { digit: 4, forms: ['四'] }, { digit: 5, forms: ['五'] }, { digit: 6, forms: ['六'] }, { digit: 7, forms: ['七'] }, { digit: 8, forms: ['八'] }, { digit: 9, forms: ['九'] } ] },
  { id: 'kk', label: 'Kazakh', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['нөл'] }, { digit: 1, forms: ['бір'] }, { digit: 2, forms: ['екі'] }, { digit: 3, forms: ['үш'] }, { digit: 4, forms: ['төрт'] }, { digit: 5, forms: ['бес'] }, { digit: 6, forms: ['алты'] }, { digit: 7, forms: ['жеті'] }, { digit: 8, forms: ['сегіз'] }, { digit: 9, forms: ['тоғыз'] } ] },
  { id: 'ko', label: 'Korean', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '#', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['영'] }, { digit: 1, forms: ['일'] }, { digit: 2, forms: ['이'] }, { digit: 3, forms: ['삼'] }, { digit: 4, forms: ['사'] }, { digit: 5, forms: ['오'] }, { digit: 6, forms: ['육'] }, { digit: 7, forms: ['칠'] }, { digit: 8, forms: ['팔'] }, { digit: 9, forms: ['구'] } ] },
  { id: 'lt', label: 'Lithuanian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: 'Nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nulis'] }, { digit: 1, forms: ['vienas'] }, { digit: 2, forms: ['du'] }, { digit: 3, forms: ['trys'] }, { digit: 4, forms: ['keturi'] }, { digit: 5, forms: ['penki'] }, { digit: 6, forms: ['šeši'] }, { digit: 7, forms: ['septyni'] }, { digit: 8, forms: ['aštuoni'] }, { digit: 9, forms: ['devyni'] } ] },
  { id: 'nb', label: 'Norwegian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['null'] }, { digit: 1, forms: ['en', 'et'] }, { digit: 2, forms: ['to'] }, { digit: 3, forms: ['tre'] }, { digit: 4, forms: ['fire'] }, { digit: 5, forms: ['fem'] }, { digit: 6, forms: ['seks'] }, { digit: 7, forms: ['sju'] }, { digit: 8, forms: ['åtte'] }, { digit: 9, forms: ['ni'] } ] },
  { id: 'pl', label: 'Polish', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: 'nr', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['jeden'] }, { digit: 2, forms: ['dwa'] }, { digit: 3, forms: ['trzy'] }, { digit: 4, forms: ['cztery'] }, { digit: 5, forms: ['pięć'] }, { digit: 6, forms: ['sześć'] }, { digit: 7, forms: ['siedem'] }, { digit: 8, forms: ['osiem'] }, { digit: 9, forms: ['dziewięć'] } ] },
  { id: 'pt-PT', label: 'Port (PT)', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'n.º', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['um'] }, { digit: 2, forms: ['dois'] }, { digit: 3, forms: ['três'] }, { digit: 4, forms: ['quatro'] }, { digit: 5, forms: ['cinco'] }, { digit: 6, forms: ['seis'] }, { digit: 7, forms: ['sete'] }, { digit: 8, forms: ['oito'] }, { digit: 9, forms: ['nove'] } ] },
  { id: 'pt-BR', label: 'Port (BR)', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'Nº', numberSignSpacing: 'no-space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['um'] }, { digit: 2, forms: ['dois'] }, { digit: 3, forms: ['três'] }, { digit: 4, forms: ['quatro'] }, { digit: 5, forms: ['cinco'] }, { digit: 6, forms: ['seis'] }, { digit: 7, forms: ['sete'] }, { digit: 8, forms: ['oito'] }, { digit: 9, forms: ['nove'] } ] },
  { id: 'ro', label: 'Romanian', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '–', rangeSpacing: 'space', numberSign: 'nr.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['zero'] }, { digit: 1, forms: ['unu'] }, { digit: 2, forms: ['doi'] }, { digit: 3, forms: ['trei'] }, { digit: 4, forms: ['patru'] }, { digit: 5, forms: ['cinci'] }, { digit: 6, forms: ['șase'] }, { digit: 7, forms: ['șapte'] }, { digit: 8, forms: ['opt'] }, { digit: 9, forms: ['nouă'] } ] },
  { id: 'ru', label: 'Russian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '—', rangeSpacing: 'space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['ноль'] }, { digit: 1, forms: ['один'] }, { digit: 2, forms: ['два'] }, { digit: 3, forms: ['три'] }, { digit: 4, forms: ['четыре'] }, { digit: 5, forms: ['пять'] }, { digit: 6, forms: ['шесть'] }, { digit: 7, forms: ['семь'] }, { digit: 8, forms: ['восемь'] }, { digit: 9, forms: ['девять'] } ] },
  { id: 'sr', label: 'Serbian', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'бр.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['нула'] }, { digit: 1, forms: ['један'] }, { digit: 2, forms: ['два'] }, { digit: 3, forms: ['три'] }, { digit: 4, forms: ['четири'] }, { digit: 5, forms: ['пет'] }, { digit: 6, forms: ['шест'] }, { digit: 7, forms: ['седам'] }, { digit: 8, forms: ['осам'] }, { digit: 9, forms: ['девет'] } ] },
  { id: 'sk', label: 'Slovak', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'č.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nula'] }, { digit: 1, forms: ['jeden'] }, { digit: 2, forms: ['dva'] }, { digit: 3, forms: ['tri'] }, { digit: 4, forms: ['štyri'] }, { digit: 5, forms: ['päť'] }, { digit: 6, forms: ['šesť'] }, { digit: 7, forms: ['sedem'] }, { digit: 8, forms: ['osem'] }, { digit: 9, forms: ['deväť'] } ] },
  { id: 'sl', label: 'Slovenian', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '–', rangeSpacing: 'space', numberSign: 'št.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nič'] }, { digit: 1, forms: ['ena'] }, { digit: 2, forms: ['dve'] }, { digit: 3, forms: ['tri'] }, { digit: 4, forms: ['štiri'] }, { digit: 5, forms: ['pet'] }, { digit: 6, forms: ['šest'] }, { digit: 7, forms: ['sedem'] }, { digit: 8, forms: ['osem'] }, { digit: 9, forms: ['devet'] } ] },
  { id: 'es', label: 'Spanish', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['cero'] }, { digit: 1, forms: ['uno'] }, { digit: 2, forms: ['dos'] }, { digit: 3, forms: ['tres'] }, { digit: 4, forms: ['cuatro'] }, { digit: 5, forms: ['cinco'] }, { digit: 6, forms: ['seis'] }, { digit: 7, forms: ['siete'] }, { digit: 8, forms: ['ocho'] }, { digit: 9, forms: ['nueve'] } ] },
  { id: 'sv', label: 'Swedish', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'space', numberSign: 'nr', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['noll'] }, { digit: 1, forms: ['ett'] }, { digit: 2, forms: ['två'] }, { digit: 3, forms: ['tre'] }, { digit: 4, forms: ['fyra'] }, { digit: 5, forms: ['fem'] }, { digit: 6, forms: ['sex'] }, { digit: 7, forms: ['sju'] }, { digit: 8, forms: ['åtta'] }, { digit: 9, forms: ['nio'] } ] },
  { id: 'th', label: 'Thai', decimalSeparator: 'dot', thousandSeparator: 'comma', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'หมายเลข', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['ศูนย์'] }, { digit: 1, forms: ['หนึ่ง'] }, { digit: 2, forms: ['สอง'] }, { digit: 3, forms: ['สาม'] }, { digit: 4, forms: ['สี่'] }, { digit: 5, forms: ['ห้า'] }, { digit: 6, forms: ['หก'] }, { digit: 7, forms: ['เจ็ด'] }, { digit: 8, forms: ['แปด'] }, { digit: 9, forms: ['เก้า'] } ] },
  { id: 'tr', label: 'Turkish', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'no-space', numberSign: 'No.', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['sıfır'] }, { digit: 1, forms: ['bir'] }, { digit: 2, forms: ['iki'] }, { digit: 3, forms: ['üç'] }, { digit: 4, forms: ['dört'] }, { digit: 5, forms: ['beş'] }, { digit: 6, forms: ['altı'] }, { digit: 7, forms: ['yedi'] }, { digit: 8, forms: ['sekiz'] }, { digit: 9, forms: ['dokuz'] } ] },
  { id: 'uk', label: 'Ukrainian', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['нуль'] }, { digit: 1, forms: ['один'] }, { digit: 2, forms: ['два'] }, { digit: 3, forms: ['три'] }, { digit: 4, forms: ['чотири'] }, { digit: 5, forms: ['п’ять'] }, { digit: 6, forms: ['шість'] }, { digit: 7, forms: ['сім'] }, { digit: 8, forms: ['вісім'] }, { digit: 9, forms: ['дев’ять'] } ] },
  { id: 'uz', label: 'Uzbek', decimalSeparator: 'comma', thousandSeparator: 'nbsp', rangeSymbol: '–', rangeSpacing: 'no-space', numberSign: '№', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['nol'] }, { digit: 1, forms: ['bir'] }, { digit: 2, forms: ['ikki'] }, { digit: 3, forms: ['uch'] }, { digit: 4, forms: ['to\'rt'] }, { digit: 5, forms: ['besh'] }, { digit: 6, forms: ['olti'] }, { digit: 7, forms: ['yetti'] }, { digit: 8, forms: ['sakkiz'] }, { digit: 9, forms: ['to\'qqiz'] } ] },
  { id: 'vi', label: 'Vietnamese', decimalSeparator: 'comma', thousandSeparator: 'dot', rangeSymbol: '-', rangeSpacing: 'space', numberSign: 'số', numberSignSpacing: 'space', digitToTextMap: [ { digit: 0, forms: ['không'] }, { digit: 1, forms: ['một'] }, { digit: 2, forms: ['hai'] }, { digit: 3, forms: ['ba'] }, { digit: 4, forms: ['bốn'] }, { digit: 5, forms: ['năm'] }, { digit: 6, forms: ['sáu'] }, { digit: 7, forms: ['bảy'] }, { digit: 8, forms: ['tám'] }, { digit: 9, forms: ['chín'] } ] }
];

export function getNumberPreset(locale: string): NumberPreset {
  const defaultPreset = NUMBER_PRESETS.find(p => p.id === 'en-US')!;
  if (!locale) return defaultPreset;
  
  const fullMatch = NUMBER_PRESETS.find(p => p.id.toLowerCase() === locale.toLowerCase());
  if (fullMatch) return fullMatch;

  const langCode = locale.split('-')[0].toLowerCase();
  const shortMatch = NUMBER_PRESETS.find(p => p.id.toLowerCase() === langCode);
  return shortMatch || defaultPreset;
}
